language: c

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update -qq
  # for unit tests
  - sudo apt-get install -y check
  # for OpenSSL support
  - sudo apt-get install -y libssl-dev
  # for Curl support
  - sudo apt-get install -y libcurl4-openssl-dev
  # for XML support
  - sudo apt-get install -y libxml2-dev
  # for static code analysis
  - sudo apt-get install -y cppcheck rats
  # for test code coverage
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov
  # for reference
  - curl --version
  - xml2-config --cflags --libs

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters

script:
  # - find . -type f -name "*.c" -print | grep -v t\/ | xargs cppcheck 2>&1
  # - find . -type f -name "*.c" -print | grep -v t\/ | xargs rats --language=c
  - git clone --depth 10 https://github.com/proftpd/proftpd.git
  - mkdir -p proftpd/contrib/mod_aws/
  - cp *.[ch] proftpd/contrib/mod_aws/
  - mkdir -p proftpd/contrib/mod_aws/cloudwatch/
  - cp cloudwatch/*.[ch] proftpd/contrib/mod_aws/cloudwatch/
  - cp mod_aws.* proftpd/contrib/mod_aws/
  - cp Makefile.in proftpd/contrib/mod_aws/
  - cp config* proftpd/contrib/mod_aws/
  - cp install-sh proftpd/contrib/mod_aws/
  - cp -R t/ proftpd/contrib/mod_aws/t/
  - cd proftpd
  - ./configure LIBS='-lm -lrt -pthread' --enable-devel=coverage --enable-dso --enable-openssl --enable-tests --with-shared=mod_aws --with-includes=/usr/include/libxml2
  - make
  # Last, a build with a static module, and run the tests
  - make clean
  - ./configure LIBS='-lm -lrt -pthread' --enable-devel=coverage --enable-openssl --enable-tests --with-modules=mod_aws --with-includes=/usr/include/libxml2
  - make
  - cd contrib/mod_aws && make TEST_VERBOSE=1 check && cd ../../

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  # capture the test coverage info
  - lcov --ignore-errors gcov,source --base-directory ${TRAVIS_BUILD_DIR}/proftpd/contrib/mod_aws --directory proftpd/contrib/mod_aws --capture --output-file coverage.info
  # filter out system and test code
  - lcov --remove coverage.info 'api/*' 't/*' '/usr/*' --output-file coverage.info
  # debug before upload
  - lcov --list coverage.info
  # upload coverage info to coveralls
  - coveralls-lcov coverage.info
